/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SearchRouteImport } from './routes/search'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as IndexRouteImport } from './routes/index'
import { Route as KnowledgeBaseIndexRouteImport } from './routes/knowledge-base.index'
import { Route as KnowledgeBaseNewRouteImport } from './routes/knowledge-base.new'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const KnowledgeBaseIndexRoute = KnowledgeBaseIndexRouteImport.update({
  id: '/knowledge-base/',
  path: '/knowledge-base/',
  getParentRoute: () => rootRouteImport,
} as any)
const KnowledgeBaseNewRoute = KnowledgeBaseNewRouteImport.update({
  id: '/knowledge-base/new',
  path: '/knowledge-base/new',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/knowledge-base/new': typeof KnowledgeBaseNewRoute
  '/knowledge-base/': typeof KnowledgeBaseIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/knowledge-base/new': typeof KnowledgeBaseNewRoute
  '/knowledge-base': typeof KnowledgeBaseIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/knowledge-base/new': typeof KnowledgeBaseNewRoute
  '/knowledge-base/': typeof KnowledgeBaseIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/chat'
    | '/search'
    | '/settings'
    | '/knowledge-base/new'
    | '/knowledge-base/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/chat'
    | '/search'
    | '/settings'
    | '/knowledge-base/new'
    | '/knowledge-base'
  id:
    | '__root__'
    | '/'
    | '/chat'
    | '/search'
    | '/settings'
    | '/knowledge-base/new'
    | '/knowledge-base/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChatRoute: typeof ChatRoute
  SearchRoute: typeof SearchRoute
  SettingsRoute: typeof SettingsRoute
  KnowledgeBaseNewRoute: typeof KnowledgeBaseNewRoute
  KnowledgeBaseIndexRoute: typeof KnowledgeBaseIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/knowledge-base/': {
      id: '/knowledge-base/'
      path: '/knowledge-base'
      fullPath: '/knowledge-base/'
      preLoaderRoute: typeof KnowledgeBaseIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/knowledge-base/new': {
      id: '/knowledge-base/new'
      path: '/knowledge-base/new'
      fullPath: '/knowledge-base/new'
      preLoaderRoute: typeof KnowledgeBaseNewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChatRoute: ChatRoute,
  SearchRoute: SearchRoute,
  SettingsRoute: SettingsRoute,
  KnowledgeBaseNewRoute: KnowledgeBaseNewRoute,
  KnowledgeBaseIndexRoute: KnowledgeBaseIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
